spring.application.name=Grocery App

spring.datasource.url=jdbc:h2:mem:grocerydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (web UI)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL Queries in console
spring.jpa.show-sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/grocerydb
